# SPDX-License-Identifier: GPL-2.0+
# Copyright 2019-2021 Airoha.

obj-$(CONFIG_PHY_AIROHA_EN8811H) += an8811h/
obj-y += arht_eth.o
obj-y += arht_eth_phy.o
obj-y += skbuff.o
obj-y += tcswitch.o
obj-y += multiupgrade.o
